server:
  port: 8081

logging.level:
  de.lab.inventory: DEBUG
  org.springframework: WARN

# Spring configuration
spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: validate
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        default_schema: s4dx_db
    show-sql: true
  # Flyway db db config
  flyway:
    baseline-on-migrate: true
    enabled: true
    schemas: s4dx_db
  # Datasource
  datasource:
    url: jdbc:h2:mem:s4dx_db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
